### ISSUE TITLE
How did you labeled the mood in data_moods?

### ISSUE THREAD

**Issue by Mathgife** [cristobalvch/Spotify-Playlists#1]
Hi!

Very interesting project!

I saw the you can obtain the energetic/relaxed intensity [here](https://towardsdatascience.com/clustering-music-to-create-your-personal-playlists-on-spotify-using-python-and-k-means-a39c4158589a)  , by seeing this other medium [article](https://towardsdatascience.com/predicting-the-music-mood-of-a-song-with-deep-learning-c3ac2b45229e) I saw that you used this [paper](https://sites.tufts.edu/eeseniordesignhandbook/2015/music-mood-classification/) to calculate the mood. However how did you obtained the "Strees" data in order to classify in Sad, Happy, Energetic, Calm?

Was it from a simple search on spotify with the label names? How did you labeled the mood in data_moods?

**Comment by cristobalvch** [comment]
Hey! I just search on spotify for  playlists with moods on their titles . Ex: Calm music, Metal Music, etc. Then I downloaded the music of the playlists and then I tagged the tracks with the mood
